// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanielaMora_Examen.Migrations
{
    [DbContext(typeof(DanielaMoraDB_Context))]
    [Migration("20240424170505_DanielaMora_DB")]
    partial class DanielaMora_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanielaMora_Examen.Models.DM_tabla1", b =>
                {
                    b.Property<int>("IdDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDm"));

                    b.Property<string>("DM_Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DM_CitaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DM_CuentaAhorro")
                        .HasColumnType("bit");

                    b.Property<bool>("DM_CuentaCorriente")
                        .HasColumnType("bit");

                    b.Property<decimal>("DM_DineroDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DM_Nombres")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDm");

                    b.ToTable("DM_tabla1");
                });
#pragma warning restore 612, 618
        }
    }
}
