// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanielaMora_Examen.Migrations
{
    [DbContext(typeof(DanielaMoraDB_Context))]
    partial class DanielaMoraDB_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanielaMora_Examen.Models.DM_tabla1", b =>
                {
                    b.Property<int>("IdDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDm"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CitaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CuentaAhorro")
                        .HasColumnType("bit");

                    b.Property<bool>("CuentaCorriente")
                        .HasColumnType("bit");

                    b.Property<decimal>("DineroDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDm");

                    b.ToTable("DM_tabla1");
                });
#pragma warning restore 612, 618
        }
    }
}
